# Generated by Django 5.0.6 on 2024-07-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Айди занятости')),
                ('name', models.CharField(max_length=150, verbose_name='Выбор занятости')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Айди опыта')),
                ('name', models.CharField(max_length=150, verbose_name='Выбор опыта')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Айди графика работы')),
                ('name', models.CharField(max_length=150, verbose_name='Выбор графика работы')),
            ],
        ),
    ]
