# Generated by Django 5.0.6 on 2024-07-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Айди вакансии')),
                ('name', models.CharField(max_length=300, verbose_name='Название вакансии')),
                ('alternate_url', models.CharField(max_length=2000, verbose_name='Ссылка на представление вакансии на сайте')),
                ('apply_alternate_url', models.CharField(max_length=2000, verbose_name='Ссылка на отклик на вакансию на сайте')),
                ('published_at', models.DateTimeField(verbose_name='Дата и время публикации вакансии')),
            ],
        ),
    ]
